### ISSUE TITLE
Custom examples not working when file is generated

### ISSUE THREAD

**Issue by lenartgolob** [asyncapi/generator#1060] opened 2023-11-06 13:34 UTC
#### Describe the bug
I defined custom payload example, but when I generate documentation from html template, the examples are generic ("string", 0, "timestamp").
#### How to Reproduce
I define my examples in messages like this:
HelpDeskTicketUserRaised:
  name: HelpDeskTicketUserRaised
  title: Help Desk Ticket User Raised
  traits:
    - $ref: './headers.yaml#/messageTraits/commonHeaders'  
  payload:
    $ref: "./schemas.yaml#/UserRequestPayload"            
    example:
      UserRequestId: 1
      Number: T-2023/241
      UserRequestMessage: '20'
      ReportedBy:
        User:
          Id: 2
          Email: john.doe@gmail.com
          ExternalCode:

#### Expected behavior
Expected behaviour is that this data shows in generated html file instead of the generic examples. If I define the data in schema and for each attribute then it works, but in my case that is unacceptable since I have too much messages. Also I am using VS Code extension which uses the react-component and on the preview in VS Code the examples work fine. But once the html file is generated, only the generic examples show.

**Comment by derberg** [comment] 2023-11-06 19:29
Hey there, please provide a full example, or at least a formatted message that can be copy/pasted

please use markdown code formatting

**Comment by lenartgolob** [comment] 2023-11-07 10:03
```
asyncapi: '2.6.0'
info:
  title: Message Queues Documentation
  version: '1.0.0'
  description: This is a documentation for message queues
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  test:
    url: test.mykafkacluster.org:8092
    protocol: kafka-secure
    description: Test broker
    security:
      - saslScram: []
defaultContentType: application/json
channels:

  #  Session

  "{operatorId}.*.session.started":
    description: desc
    parameters:
      operatorId:
        $ref: '#/components/parameters/operatorId'
    publish:
      operationId: sessionStarted
      traits:
        - $ref: '#/components/operationTraits/kafka'
      message:
        $ref: '#/components/messages/SessionStarted'
      tags:
        - name:  Session

components:
  messages:
    SessionStarted:
      name: SessionStarted
      title: Session Started
      contentType: application/json
      traits:
        - $ref: '#/components/messageTraits/commonHeaders'
      payload:
        $ref: "#/components/schemas/SessionPayload"   
        example:
          SessionId: 660427
          SessionNumber: "S-2023/2673"
          SessionSourceId: 1
          ParkingFrom: null
          ParkingTo: null
          ConnectedFrom: "2023-10-30T07: 53: 03.557Z"
          ConnectedTo: null
          From: "2023-10-30T07: 53: 03.557Z"
          To: null
          MeterStart: 6804.3 
          MeterEnd: null
          Consumption: null
          Power: null
          RoamingTypeId: 0
          RoamingSessionId: null
          InstanceRoamingPlatformId: null
          Object: 
            Id: 75691
            ObjectFriendlyCode: "1"                 
                                                                                                                              

  schemas:
    SessionPayload:
      type: object
      properties:
        SessionId:
          type: integer
          format: int64
          description: Unique ID of the  session
        SessionNumber:
          type: string
          description: Friendly ID of the  session
        SessionSourceId:
          type: integer
          format: int16
          description: 1 - Local charge point (CSO); 2 - Roaming CDR.
        ParkingFrom:
          type: string
          format: date-time
          description: Parking start time. Normally empty if charger is not able to detect parking time.
        ParkingTo:
          type: string
          format: date-time
          description: Parking end time. Normally empty if charger is not able to detect parking time.
        ConnectedFrom:
          type: string
          format: date-time
        ConnectedTo:
          type: string
          format: date-time
        From:
          type: string
          format: date-time
        To:
          type: string
          format: date-time
        MeterStart:
          type: string
          format: date-time
        MeterEnd:
          type: string
          format: date-time
        Consumption:
          type: number
          format: float
        Power:
          type: number
          format: float
        RoamingTypeId:
          type: integer
          format: int32
        RoamingSessionId:
          type: string
          description: Roaming session id, collected from roaming partner, used as reference when communicating with partner.
        InstanceRoamingPlatformId:
          type: integer
          format: int32
        Object:
          type: object
          properties:
            Id:
              type: integer
              format: int32
            ObjectFriendlyCode:
              type: string
  
  securitySchemes:
    saslScram:
      type: scramSha256
      description: Provide your username and password for SASL/SCRAM authentication
  parameters:
    operatorId:
      description: Instance ID. Every tenant has unique ID.
      schema:
        type: integer
        format: int32                
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          my-app-header:
            type: integer
            minimum: 0
            maximum: 100
  operationTraits:
    kafka:
      bindings:
        kafka:
          clientId: my-app-id
```

This is the sample document (full document is too long). There are no error, the file gets generated, but the examples are generic instead of the examples I listed. I want the generated html file to have the example I listed. When I preview the async file with VS Code Extension the examples are the ones I defined and not generated ones, but once I generate html file the genric examples show up. Also defining example for each attribute is really not an option, because the file is so long and examples are also very long.

**Comment by derberg** [comment] 2024-01-17 17:12
@derberg sorry for such a late response but we were in the middle of asyncapi v3 release and then also christmas break

the problem is that you provide example in not a valid asyncapi way


your message should look like:
```yaml
    SessionStarted:
      name: SessionStarted
      title: Session Started
      contentType: application/json
      traits:
        - $ref: '#/components/messageTraits/commonHeaders'
      payload:
        $ref: "#/components/schemas/SessionPayload"   
      examples:
        - payload:
            SessionId: 660427
            SessionNumber: "S-2023/2673"
            SessionSourceId: 1
            ParkingFrom: null
            ParkingTo: null
            ConnectedFrom: "2023-10-30T07: 53: 03.557Z"
            ConnectedTo: null
            From: "2023-10-30T07: 53: 03.557Z"
            To: null
            MeterStart: 6804.3 
            MeterEnd: null
            Consumption: null
            Power: null
            RoamingTypeId: 0
            RoamingSessionId: null
            InstanceRoamingPlatformId: null
            Object: 
              Id: 75691
              ObjectFriendlyCode: "1"      
```

since message can also have headers, then an example object has a structure that enable you to provide example of header and payload separately + you can have multiple examples -> https://v2.asyncapi.com/docs/reference/specification/v2.6.0#messageExampleObject

[here you can see fixed document](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6ICcyLjYuMCcKaW5mbzoKICB0aXRsZTogTWVzc2FnZSBRdWV1ZXMgRG9jdW1lbnRhdGlvbgogIHZlcnNpb246ICcxLjAuMCcKICBkZXNjcmlwdGlvbjogVGhpcyBpcyBhIGRvY3VtZW50YXRpb24gZm9yIG1lc3NhZ2UgcXVldWVzCiAgbGljZW5zZToKICAgIG5hbWU6IEFwYWNoZSAyLjAKICAgIHVybDogaHR0cHM6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMApzZXJ2ZXJzOgogIHRlc3Q6CiAgICB1cmw6IHRlc3QubXlrYWZrYWNsdXN0ZXIub3JnOjgwOTIKICAgIHByb3RvY29sOiBrYWZrYS1zZWN1cmUKICAgIGRlc2NyaXB0aW9uOiBUZXN0IGJyb2tlcgogICAgc2VjdXJpdHk6CiAgICAgIC0gc2FzbFNjcmFtOiBbXQpkZWZhdWx0Q29udGVudFR5cGU6IGFwcGxpY2F0aW9uL2pzb24KY2hhbm5lbHM6CgogICMgIFNlc3Npb24KCiAgIntvcGVyYXRvcklkfS4qLnNlc3Npb24uc3RhcnRlZCI6CiAgICBkZXNjcmlwdGlvbjogZGVzYwogICAgcGFyYW1ldGVyczoKICAgICAgb3BlcmF0b3JJZDoKICAgICAgICAkcmVmOiAnIy9jb21wb25lbnRzL3BhcmFtZXRlcnMvb3BlcmF0b3JJZCcKICAgIHB1Ymxpc2g6CiAgICAgIG9wZXJhdGlvbklkOiBzZXNzaW9uU3RhcnRlZAogICAgICB0cmFpdHM6CiAgICAgICAgLSAkcmVmOiAnIy9jb21wb25lbnRzL29wZXJhdGlvblRyYWl0cy9rYWZrYScKICAgICAgbWVzc2FnZToKICAgICAgICAkcmVmOiAnIy9jb21wb25lbnRzL21lc3NhZ2VzL1Nlc3Npb25TdGFydGVkJwogICAgICB0YWdzOgogICAgICAgIC0gbmFtZTogIFNlc3Npb24KCmNvbXBvbmVudHM6CiAgbWVzc2FnZXM6CiAgICBTZXNzaW9uU3RhcnRlZDoKICAgICAgbmFtZTogU2Vzc2lvblN0YXJ0ZWQKICAgICAgdGl0bGU6IFNlc3Npb24gU3RhcnRlZAogICAgICBjb250ZW50VHlwZTogYXBwbGljYXRpb24vanNvbgogICAgICB0cmFpdHM6CiAgICAgICAgLSAkcmVmOiAnIy9jb21wb25lbnRzL21lc3NhZ2VUcmFpdHMvY29tbW9uSGVhZGVycycKICAgICAgcGF5bG9hZDoKICAgICAgICAkcmVmOiAiIy9jb21wb25lbnRzL3NjaGVtYXMvU2Vzc2lvblBheWxvYWQiICAgCiAgICAgIGV4YW1wbGVzOgogICAgICAgIC0gcGF5bG9hZDoKICAgICAgICAgICAgU2Vzc2lvbklkOiA2NjA0MjcKICAgICAgICAgICAgU2Vzc2lvbk51bWJlcjogIlMtMjAyMy8yNjczIgogICAgICAgICAgICBTZXNzaW9uU291cmNlSWQ6IDEKICAgICAgICAgICAgUGFya2luZ0Zyb206IG51bGwKICAgICAgICAgICAgUGFya2luZ1RvOiBudWxsCiAgICAgICAgICAgIENvbm5lY3RlZEZyb206ICIyMDIzLTEwLTMwVDA3OiA1MzogMDMuNTU3WiIKICAgICAgICAgICAgQ29ubmVjdGVkVG86IG51bGwKICAgICAgICAgICAgRnJvbTogIjIwMjMtMTAtMzBUMDc6IDUzOiAwMy41NTdaIgogICAgICAgICAgICBUbzogbnVsbAogICAgICAgICAgICBNZXRlclN0YXJ0OiA2ODA0LjMgCiAgICAgICAgICAgIE1ldGVyRW5kOiBudWxsCiAgICAgICAgICAgIENvbnN1bXB0aW9uOiBudWxsCiAgICAgICAgICAgIFBvd2VyOiBudWxsCiAgICAgICAgICAgIFJvYW1pbmdUeXBlSWQ6IDAKICAgICAgICAgICAgUm9hbWluZ1Nlc3Npb25JZDogbnVsbAogICAgICAgICAgICBJbnN0YW5jZVJvYW1pbmdQbGF0Zm9ybUlkOiBudWxsCiAgICAgICAgICAgIE9iamVjdDogCiAgICAgICAgICAgICAgSWQ6IDc1NjkxCiAgICAgICAgICAgICAgT2JqZWN0RnJpZW5kbHlDb2RlOiAiMSIgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKCiAgc2NoZW1hczoKICAgIFNlc3Npb25QYXlsb2FkOgogICAgICB0eXBlOiBvYmplY3QKICAgICAgcHJvcGVydGllczoKICAgICAgICBTZXNzaW9uSWQ6CiAgICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgICAgICBmb3JtYXQ6IGludDY0CiAgICAgICAgICBkZXNjcmlwdGlvbjogVW5pcXVlIElEIG9mIHRoZSAgc2Vzc2lvbgogICAgICAgIFNlc3Npb25OdW1iZXI6CiAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgIGRlc2NyaXB0aW9uOiBGcmllbmRseSBJRCBvZiB0aGUgIHNlc3Npb24KICAgICAgICBTZXNzaW9uU291cmNlSWQ6CiAgICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgICAgICBmb3JtYXQ6IGludDE2CiAgICAgICAgICBkZXNjcmlwdGlvbjogMSAtIExvY2FsIGNoYXJnZSBwb2ludCAoQ1NPKTsgMiAtIFJvYW1pbmcgQ0RSLgogICAgICAgIFBhcmtpbmdGcm9tOgogICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICBmb3JtYXQ6IGRhdGUtdGltZQogICAgICAgICAgZGVzY3JpcHRpb246IFBhcmtpbmcgc3RhcnQgdGltZS4gTm9ybWFsbHkgZW1wdHkgaWYgY2hhcmdlciBpcyBub3QgYWJsZSB0byBkZXRlY3QgcGFya2luZyB0aW1lLgogICAgICAgIFBhcmtpbmdUbzoKICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgICAgZm9ybWF0OiBkYXRlLXRpbWUKICAgICAgICAgIGRlc2NyaXB0aW9uOiBQYXJraW5nIGVuZCB0aW1lLiBOb3JtYWxseSBlbXB0eSBpZiBjaGFyZ2VyIGlzIG5vdCBhYmxlIHRvIGRldGVjdCBwYXJraW5nIHRpbWUuCiAgICAgICAgQ29ubmVjdGVkRnJvbToKICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgICAgZm9ybWF0OiBkYXRlLXRpbWUKICAgICAgICBDb25uZWN0ZWRUbzoKICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgICAgZm9ybWF0OiBkYXRlLXRpbWUKICAgICAgICBGcm9tOgogICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICBmb3JtYXQ6IGRhdGUtdGltZQogICAgICAgIFRvOgogICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICBmb3JtYXQ6IGRhdGUtdGltZQogICAgICAgIE1ldGVyU3RhcnQ6CiAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgIGZvcm1hdDogZGF0ZS10aW1lCiAgICAgICAgTWV0ZXJFbmQ6CiAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgIGZvcm1hdDogZGF0ZS10aW1lCiAgICAgICAgQ29uc3VtcHRpb246CiAgICAgICAgICB0eXBlOiBudW1iZXIKICAgICAgICAgIGZvcm1hdDogZmxvYXQKICAgICAgICBQb3dlcjoKICAgICAgICAgIHR5cGU6IG51bWJlcgogICAgICAgICAgZm9ybWF0OiBmbG9hdAogICAgICAgIFJvYW1pbmdUeXBlSWQ6CiAgICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgICAgICBmb3JtYXQ6IGludDMyCiAgICAgICAgUm9hbWluZ1Nlc3Npb25JZDoKICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgICAgZGVzY3JpcHRpb246IFJvYW1pbmcgc2Vzc2lvbiBpZCwgY29sbGVjdGVkIGZyb20gcm9hbWluZyBwYXJ0bmVyLCB1c2VkIGFzIHJlZmVyZW5jZSB3aGVuIGNvbW11bmljYXRpbmcgd2l0aCBwYXJ0bmVyLgogICAgICAgIEluc3RhbmNlUm9hbWluZ1BsYXRmb3JtSWQ6CiAgICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgICAgICBmb3JtYXQ6IGludDMyCiAgICAgICAgT2JqZWN0OgogICAgICAgICAgdHlwZTogb2JqZWN0CiAgICAgICAgICBwcm9wZXJ0aWVzOgogICAgICAgICAgICBJZDoKICAgICAgICAgICAgICB0eXBlOiBpbnRlZ2VyCiAgICAgICAgICAgICAgZm9ybWF0OiBpbnQzMgogICAgICAgICAgICBPYmplY3RGcmllbmRseUNvZGU6CiAgICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgCiAgc2VjdXJpdHlTY2hlbWVzOgogICAgc2FzbFNjcmFtOgogICAgICB0eXBlOiBzY3JhbVNoYTI1NgogICAgICBkZXNjcmlwdGlvbjogUHJvdmlkZSB5b3VyIHVzZXJuYW1lIGFuZCBwYXNzd29yZCBmb3IgU0FTTC9TQ1JBTSBhdXRoZW50aWNhdGlvbgogIHBhcmFtZXRlcnM6CiAgICBvcGVyYXRvcklkOgogICAgICBkZXNjcmlwdGlvbjogSW5zdGFuY2UgSUQuIEV2ZXJ5IHRlbmFudCBoYXMgdW5pcXVlIElELgogICAgICBzY2hlbWE6CiAgICAgICAgdHlwZTogaW50ZWdlcgogICAgICAgIGZvcm1hdDogaW50MzIgICAgICAgICAgICAgICAgCiAgbWVzc2FnZVRyYWl0czoKICAgIGNvbW1vbkhlYWRlcnM6CiAgICAgIGhlYWRlcnM6CiAgICAgICAgdHlwZTogb2JqZWN0CiAgICAgICAgcHJvcGVydGllczoKICAgICAgICAgIG15LWFwcC1oZWFkZXI6CiAgICAgICAgICAgIHR5cGU6IGludGVnZXIKICAgICAgICAgICAgbWluaW11bTogMAogICAgICAgICAgICBtYXhpbXVtOiAxMDAKICBvcGVyYXRpb25UcmFpdHM6CiAgICBrYWZrYToKICAgICAgYmluZGluZ3M6CiAgICAgICAga2Fma2E6CiAgICAgICAgICBjbGllbnRJZDogbXktYXBwLWlk) but still with errors as your example do not match provided AsyncAPI Schema

**Comment by derberg** [comment] 2024-01-25 07:54
7 days passed. I think we can assume provided solution will work. Closing. Feel free to drop a comment in case it is not really resolved

**Closed by derberg** 2024-01-25 07:54 UTC
Labels: bug
