### ISSUE TITLE
Using custom (local) template with docker seems broken

### ISSUE THREAD

**Issue by credo-janne** [asyncapi/generator#388] opened 2020-07-17 16:19 UTC
I'm trying to run the generator (docker) with a custom template on file system, but fail.

Switching to using the latest cloned master of eg html-template code from a local dir also fails. As do using a clone of the java-spring-template repo.

The command I'm running is:
`docker run --rm -v /path/to/asyncapi.yml:/app/asyncapi.yml -v /path/to/cloned/html-template:/app/custom-template -v /path/to/output:/app/output asyncapi/generator -o ./output asyncapi.yml ./custom-template --force-write`

The output I'm getting is:
```
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi%2fgenerator-filters 1119ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi/generator-filters/-/generator-filters-1.0.0.tgz 46ms
npm http fetch GET 200 https://registry.npmjs.org/markdown-it 29ms
npm http fetch GET 200 https://registry.npmjs.org/markdown-it/-/markdown-it-10.0.0.tgz 14ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/openapi-sampler 54ms
npm http fetch GET 200 https://registry.npmjs.org/openapi-sampler/-/openapi-sampler-1.0.0-beta.16.tgz 26ms
npm http fetch GET 200 https://registry.npmjs.org/entities 24ms
npm http fetch GET 200 https://registry.npmjs.org/entities/-/entities-2.0.3.tgz 21ms
npm http fetch GET 200 https://registry.npmjs.org/json-pointer 25ms
npm http fetch GET 200 https://registry.npmjs.org/json-pointer/-/json-pointer-0.6.0.tgz 34ms
npm http fetch GET 200 https://registry.npmjs.org/foreach 23ms
npm http fetch GET 200 https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz 31ms
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

Something went wrong:
Error: Cannot find module '/app/node_modules/@asyncapi/html-template/node_modules/@asyncapi/generator-filters'
Require stack:
- /app/lib/filtersRegistry.js
- /app/lib/generator.js
- /app/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /app/lib/filtersRegistry.js:74:17
    at async Promise.all (index 0)
    at async registerConfigFilters (/app/lib/filtersRegistry.js:79:3)
    at async module.exports.registerFilters (/app/lib/filtersRegistry.js:15:3)
    at async Generator.generate (/app/lib/generator.js:178:5)
    at async /app/cli.js:150:9
```
Maybe I'm misunderstanding the required setup, or have missed out on some important doc somewhere, but shouldn't I be able to run an "official" template from a local directory, if correctly mounted into the docker container?

Is this problem reproducible by you, with a spec and template that is known to be working?

Thanks.

**Comment by credo-janne** [comment] 2020-07-17 18:01
I've now tried the same command, but with the remote spec (https://raw.githubusercontent.com/asyncapi/generator/master/test/docs/dummy.yml) mentioned at https://github.com/asyncapi/generator/blob/master/docs/authoring.md. Same outcome though.

Also, running with --version gives 1.0.0-rc.5, which I guess might be useful info.

**Comment by fmvilas** [comment] 2020-07-20 10:20
🤔 I can't manage to reproduce the bug. Would you mind removing your Docker image and pulling it again?

```
docker rmi asyncapi/generator
docker run --rm -v /path/to/asyncapi.yml:/app/asyncapi.yml -v /path/to/cloned/html-template:/app/custom-template -v /path/to/output:/app/output asyncapi/generator -o ./output asyncapi.yml ./custom-template --force-write
```

**Comment by derberg** [comment] 2020-07-27 15:53
@credo-janne hey, did you try running docker with template from remote location and not local?

Your issue seems to be related to this one https://github.com/asyncapi/generator/issues/391

you can also try to go to your local template and install it manually first with `npm i` and then run docker. Just to make sure if those issues are related

**Comment by credo-janne** [comment] 2020-08-10 13:00
Hi, thanks for your response. And sorry for being unresponsive myself. Vacation periods unfortunately...

I tried the newest docker image (now running 1.0.0-rc.7), but the result is the same.

Agree with that it seems related to the same problem as described in #391. If that is the case, then this is problem is not really related to the docker packaged version, but rather the generator itself, I guess.

Unfortunately, I don't see a way to run `nmp -i` on the local template when using a containerized approach, so this problem is more of a blocker in this case, compared to running the generator directly on the host/dev box. (I don't expect the container to be affected by running `npm -i` on the local template on the host)

Reason for the container approach in my case is that I wan't to run the generator in a CI setup, without having to pre-install anything on the CI-slaves, except docker.

Any other ideas are appreciated!

**Comment by derberg** [comment] 2020-08-10 15:06
until we have this fixed the only solution for you is to use some pure nodejs docker image, and first install template dependencies with it. Here is an example https://gist.github.com/ArtemGordinsky/b79ea473e8bc6f67943b but of course with pretty old node image, use `node:12-alpine`

**Comment by credo-janne** [comment] 2020-08-13 15:19
An update.

Installing the template on the host is in fact sufficient for making the dockerized generator work too.

When installing the template on host level (`npm install` in the template directory), all resources needed for the generator will end up in the template directory on the host. Since that directory is mounted to the docker container, everything needed for the dockerized generator is in place too.

So installing the template on the host is also a valid workaround when using the dockerized generator.

**Comment by derberg** [comment] 2020-08-14 09:21
oh, I thought I want to avoid installing and using `npm`. Anyway as you said, it is still a workaround, this is why we should keep this issue open imho

**Comment by derberg** [comment] 2020-08-18 09:08
@credo-janne you might be interested with the result of my recent investigation https://github.com/asyncapi/generator/issues/391#issuecomment-675358972. You do not have to install template explicitly, just mount the template in different directory like this:

`docker run --rm -v /path/to/asyncapi.yml:/app/asyncapi.yml -v /path/to/cloned/html-template:/template/custom-template -v /path/to/output:/app/output asyncapi/generator -o ./output asyncapi.yml ../template/custom-template --force-write`

**Comment by derberg** [comment] 2020-08-19 09:55
@credo-janne I'm gonna close this one since we have 2 solid workarounds and there is no way to solve it really, we can only improve it and long term we will do it with https://github.com/asyncapi/generator/issues/399

**Closed by derberg** 2020-08-19 09:55 UTC
Labels: bug

**Comment by credo-janne** [comment] 2020-08-19 20:15
Thanks, I've verified the workaround on my side, and it does work as described.
Mounting the template to a different path than `/app` (eg to `/custom-template`) in the docker container does work without a need to run `npm -i` in the template directory on the host in advance.
