### ISSUE TITLE
Fetch templates via url and cache

### ISSUE THREAD

**Issue by johndcarmichael** [asyncapi/generator#243] opened 2020-03-07 16:45 UTC
Would be great to be able to reference templates via url as seen with https://github.com/acrontum/openapi-nodegen

**Comment by fmvilas** [comment] 2020-03-11 19:28
Duplicate of #235 

This is indeed in the roadmap before we reach v1.0.0. Thanks! :)

**Closed by fmvilas** 2020-03-11 19:28 UTC
