### ISSUE TITLE
HTML generator doesn't output multiple example messages in oneOf

### ISSUE THREAD

**Issue by sirnewton01** [asyncapi/generator#67] opened 2019-07-03 00:28 UTC
Using this example model if you generate the HTML from it you can only see one example message leaving the others hidden to the reader of the documentation.

```
# Standard header elements

channels:
  /socket/{subscription_id}:
    parameters:
      - name: subscription_id
        schema:
          type: string
    publish:
      message:
        oneOf:
          - summary: Register subscription
            contentType: application/json
            payload:
              type: object
              properties:
                name:
                  type: string
                  enum: [register]
          - summary: Send still alive message to the Hive.
            contentType: application/json
            payload:
              type: object
              properties:
                name:
                  type: string
                  enum: [still_alive]
                payload:
                  type: object
                  properties:
                    id:
                      type: string
                      description: This is the id from the keep_alive message.
```

**Comment by jonaslagoni** [comment] 2019-11-08 21:54
I am not able to reproduce this in 2.0.0 with the following specification:
![image](https://user-images.githubusercontent.com/13396189/68513173-a07c7c80-027a-11ea-9d61-5b965c1bfe91.png)

**Comment by derberg** [comment] 2020-02-15 18:10
@sirnewton01 looking on @jonaslagoni comment and his investigation, it appears the issue is no longer valid. I will close it but feel free to reopen in case you can still reproduce it (and describe how to do it). Thanks a lot.

**Closed by derberg** 2020-02-15 18:10 UTC
Labels: help wanted
