### ISSUE TITLE
Unable to run generator as Docker image

### ISSUE THREAD

**Issue by YBogomolov** [asyncapi/generator#79] opened 2019-08-14 10:28 UTC
## Environment:
– macOS Mojave 10.14.6
– docker 19.03.1

## Steps to reproduce:
1. Execute command from the README:  
```sh
docker run --rm -it -v $PWD:/app -w /app asyncapi/generator -V
```

## Actual result:

```
docker run --rm -it -v $PWD:/app -w /app asyncapi/generator -V
Unable to find image 'asyncapi/generator:latest' locally
docker: Error response from daemon: pull access denied for asyncapi/generator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

## Expected result:

Generator version is written on the terminal.

**Comment by fmvilas** [comment] 2019-08-14 10:38
That is because we don't have this Docker image on Docker Hub. See: https://hub.docker.com/r/asyncapi/generator. We don't yet maintain any Docker images.

@treeder is it you who registered the `asyncapi` user?

Closing as duplicate of #68

**Comment by YBogomolov** [comment] 2019-08-14 11:33
Then, maybe, it's worth removing the command to run the generator using Docker from Readme? It's really misleading.

**Comment by fmvilas** [comment] 2019-08-14 11:35
Sorry, it looks like it was already addressed #68 but for some reason, it hasn't been published to Docker Hub. Pinging @treeder.

**Comment by treeder** [comment] 2019-08-14 14:13
On it...

**Comment by treeder** [comment] 2019-08-14 14:35
Should we assume [node-codeden](https://github.com/asyncapi/node-codegen) is obsolete?  If so, I can remove it and simplify this image.

**Comment by treeder** [comment] 2019-08-14 14:49
Image pushed, need to include `ag` or `anc` command:

```
docker run --rm -it -v $PWD:/app -w /app asyncapi/generator ag -V
```

**Closed** 2019-08-14 16:40 UTC
Labels: bug

**Comment by fmvilas** [comment] 2019-08-14 16:42
> Should we assume node-codeden is obsolete?

Yes, node-codegen is obsolete. We should migrate it to generator at some point.

> Image pushed, need to include ag or anc command

This is awesome! Thanks!
