### ISSUE TITLE
parser 1.0.2 incompatible with current generator

### ISSUE THREAD

**Issue by djencks** [asyncapi/generator#435] opened 2020-10-28 01:18 UTC
#### Describe the bug
Using parser 1.0.2 with generator 1.0.0-rc.13 results in errors:
```
Error: Parameter "asyncapiDocument" must be an AsyncAPIDocument object.
    at Generator.generate (/Users/david/projects/antora/extensions/asyncapi/antora-asyncapi/node_modules/@asyncapi/generator/lib/generator.js:154:64)
    at generate (/Users/david/projects/antora/extensions/asyncapi/antora-asyncapi/lib/antora-asyncapi.js:107:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### How to Reproduce
package.json:
```
    "@asyncapi/generator": "1.0.0-rc.13",
    "@asyncapi/parser": "1.0.2",
```
code:
```
      const parsed = await parser.parse(sourceString)
      const asciidoc = await generator.generate(parsed)
```

To see this in action, clone https://gitlab.com/djencks/antora-asyncapi, change the version of the parser to 1.0.2, run npm i, clone https://gitlab.com/djencks/antora-extension-examples, in antora-asyncapi change the location of @djencks/antora-asyncapi to the file system location, and run npm run clean-build.

#### Expected behavior
I expected my code to continue to work as you guys released upgrades.

I suggest that you have the generator export the parser it uses so I don't have to try to keep versions in sync:
```
module.exports = Generator;
module.exports.parse = parse;
```
Then I can get the correct version of the parser easily without having to try to keep up with whatever you are doing.

**Comment by derberg** [comment] 2020-10-28 11:45
@djencks Hi, please share a bit more information. Please answer below questions:

- Do you mean parser 1.0.1 worked but 1.0.2 doesn't? 1.0.2 is a patch, it changed nothing in AsyncAPIDocument object at all.
- Wouldn't it be easier for you to use `generateFromString` function and let generator parse it for you? The generator also uses AsyncAPI Parser

**Comment by djencks** [comment] 2020-10-28 20:39
- Yes, using the exact version of parser as the generator uses works, using 1.0.2 does not.  Javascript classes are still a bit of a mystery to me, but I suspect that at least in node a class retains information about the module from which it was loaded, so, as in Java, class name and code identity is not enough to establish class equality.
- I can (and will) use generateFromString, but I think it would be convenient for someone who needs to examine the AsyncApiDocument object as well as generate from it to be able to get a compatible parser automatically.  I was using separate steps to attempt to time the phases, but this information is not very useful.

**Comment by djencks** [comment] 2020-10-28 22:05
Actually I can't realistically use generateFromString because I need to generate multiple documents from the same source asyncapi file.

Adding a parse method to the Generator class that delegates to the parser might be cleaner than an additional export.

**Comment by djencks** [comment] 2020-10-29 03:09
Apparently I can omit the dependency on @asyncapi/parser or list it as a peerDependency and get the version installed by @asyncapi/generator.  However, at this point I think that exposing one or more parse methods on the generator is cleaner.  If you agree I'd be happy to supply a PR.

**Comment by djencks** [comment] 2020-10-29 07:41
I appear to have spoken too soon, and that I didn't clean up my environment sufficiently.  I don't think the peerDependencies idea works after all.

**Comment by derberg** [comment] 2020-10-29 13:34
@djencks you know what, I created a very simple basic project -> https://github.com/derberg/simple-example-generator-with-parser and to be honest, it could never work. I checked many parser versions, even went back to 0.18 version and still error is 
```
Error: Parameter "asyncapiDocument" must be an AsyncAPIDocument object.
    at Generator.generate (/Users/wookiee/sources/simple-example-generator-with-parser/node_modules/@asyncapi/generator/lib/generator.js:154:64)
    at run (/Users/wookiee/sources/simple-example-generator-with-parser/index.js:20:21)
```

The orygin of the problem is https://github.com/asyncapi/generator/blob/master/lib/generator.js#L154. Maybe instead of `!(asyncapiDocument instanceof AsyncAPIDocument)` we should just do `asyncapiDocument.constructor.name !== 'AsyncAPIDocument'`

---

Regarding using `generateFromString`. What do you mean here
```
Actually I can't realistically use generateFromString because I need to generate multiple documents from the same source asyncapi file.
```
`generateFromString` is not much different than `generate` -> https://github.com/asyncapi/generator/blob/master/lib/generator.js#L229-L238. It just does what you did manually, parses docs and passes it to `generate` function

**Comment by djencks** [comment] 2020-10-29 21:20
I can't explain your results. My project works fine when the versions of the generator and parser are fixed and the parser version is 1.0.1, same as the generator.

It also works fine with my first proposed solution, exporting the parse method from the generator and using that instead of a separate parser.

Parsing appears to take a significant amount of time, so I do (pseudocode)
```
const doc = await parse(source)
const output1 = await generate(doc, template1)
const output2 = await generate(doc, template2)
```

**Comment by rv0** [comment] 2020-10-29 21:24
I can vouch in here here to say that @djencks project is working fine for me as well in the configuration he describes.
(I was the one who reported the initial error to him)

**Comment by derberg** [comment] 2020-10-30 11:28
@djencks thanks for the pseudocode example, it pretty clearly explained the used case 🙇 

For me it is a valid use case for exposing internally used parser in the generator API. I also do not have a strong opinion though, if this is the best solution or maybe others would be better, so let me ask others.

@fmvilas @jonaslagoni could one of you share opinion. I'm totally fine with exposing parser in Generator API as the use case is completely valid

**Comment by jonaslagoni** [comment] 2020-11-03 20:47
Yea I think we can expose the parser methods. Don't see any downsides doing this, unless you guys see a use-case where you want manually use a different version then the underlying parser 🤔?

**Comment by derberg** [comment] 2020-11-04 09:01
I definitely do not see a valid use case using a separate parser, so the best approach to solve @djencks use case is to expose the parser used by the Generator

**Comment by derberg** [comment] 2020-11-12 17:34
@djencks hey, generator 1.0.0 is out, you can start working on exposing parser as part of generator API

**Comment by derberg** [comment] 2021-01-12 08:31
@djencks hey, did you plan to work on this one?

**Comment by derberg** [comment] 2021-02-09 08:56
@djencks hey, do you plan to work on this one or shall we close it?

**Comment by djencks** [comment] 2021-02-09 19:37
It turns out for my use case it doesn't make any sense to use the Generator, it is much much simpler to use the parser directly and manage templates myself.  Therefore, I don't expect to work on this any more.

**Closed** 2021-04-12 08:16 UTC
Labels: enhancement
